[package]
name = "tontine_cbor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
wasm-bindgen = "0.2.78"
cardano-serialization-lib = { git = "https://github.com/Emurgo/cardano-serialization-lib.git" }


